#!/bin/bash
# Sets SLINK_HOST and SLINK_AUTH for an admin user.
# Usage: source $0 [HANDLE] [AUTH]
echo "Setting SLINK_HOST to the pds of $1."
export SLINK_HOST=$(slink resolve pds $1)
echo "Setting SLINK_AUTH to the admin of $SLINK_HOST using the specified password."
export SLINK_AUTH="Basic $(echo -n "admin:$2" | base64)"
